[package]
name = "pointercrate"
version = "0.1.0"
edition = "2018"
build = "build_documentation.rs"

[dependencies]
sqlx = { version = "0.4.1", default-features = false, features = [ "runtime-tokio-native-tls", "macros", "postgres", "chrono" ] }
actix-web = "2.0.0"
maud = "0.21.0"
reqwest = "0.10.3"
actix-files = "0.2.1"
log = "0.4.8"
serde = "1.0.104"
mime = "0.3.16"
actix-web-codegen = "0.2.1"
serde_json = "1.0.48"
bitflags = "1.2.1"
derive_more = "0.99.3"
futures = "0.3.4"
jsonwebtoken = "7.0.1"
base64 = "0.11.0"
lazy_static = "1.4.0"
nonzero_ext = "0.2.0"
ratelimit_meter = "5.0.0"
url = "2.1.1"
actix-rt = "1.0.0"
serde_urlencoded = "0.6.1"
bcrypt = "0.6.1"
env_logger = "0.7.1"
dotenv = "0.15.0"
chrono = "0.4.10"
bincode = "1.3.1"

[dependencies.dash-rs]
git = "https://github.com/stadust/dash-rs"
